# Generated by Django 5.2.16 on 2026-07-22 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_accessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=240)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='accounts.companymembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_locations', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reconciliation_cutoff', models.DateField()),
                ('state', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('reconciliation', 'Reconciliation'), ('final', 'Final')], default='upcoming', max_length=20)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='accounts.company')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('base_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='work_logs.baselocation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to='accounts.companymembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='work_logs.project')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('assignment_status', models.CharField(choices=[('benched', 'Benched'), ('same_base', 'Same base'), ('different_base', 'Different base')], max_length=20)),
                ('expected_fraction', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_status_rules', to='accounts.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteWorkException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=240)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='accounts.companymembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkInOfficeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('location_choice', models.CharField(blank=True, choices=[('in_office', 'In office'), ('not_in_office', 'Not in office')], max_length=20, null=True)),
                ('review_state', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_required', 'Not required')], default='draft', max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('approver_note', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignment_snapshot', models.JSONField(blank=True, default=dict)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wio_records', to='accounts.companymembership')),
            ],
            options={
                'ordering': ['-work_date', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='baselocation',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='work_logs_location_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='companyholiday',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='work_logs_holiday_unique'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='work_logs_period_company_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('company',), name='work_logs_one_active_period'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='work_logs_project_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='workinofficerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date'), name='work_logs_one_record_per_employee_day'),
        ),
    ]
