# Generated by Django 5.2.16 on 2026-07-20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_otprequestratelimit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTPRequestRateLimit",
        ),
    ]
