# Generated by Django 5.2.16 on 2026-07-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accessrequest'),
        ('work_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='work_logs.baselocation'),
        ),
    ]
